import { useSyncExternalStore } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { Card, Pill } from '@/components/ui'
import { setupStore } from './store'

export function SetupPreview() {
  const s = useSyncExternalStore(setupStore.subscribe, setupStore.getSnapshot)
  const ai = useLocation().pathname.endsWith('/ai')
  return <div className="mx-auto max-w-4xl space-y-6 pb-64">
    <header><Pill>Deployment preview · Simulated</Pill><h1 className="mt-3 text-display-xs font-semibold text-primary">{ai ? 'AI setup & readiness' : 'Repository events & analysis'}</h1><p className="mt-3 max-w-3xl text-sm leading-relaxed text-secondary">{ai ? 'Understand the deployment prerequisites, inspect readiness and review an existing evidence record. This preview does not save production settings or contact an AI provider.' : 'Connect source access and delivery events separately. This preview explains the deployment handoff; the guided example records events only in this browser.'}</p></header>
    {ai && <nav aria-label="AI setup path" className="flex flex-wrap items-center gap-2 text-sm text-tertiary"><span>Engagements</span><span aria-hidden="true">/</span><span>synapse-ce-audit</span><span aria-hidden="true">/</span><span>Offensive</span><span aria-hidden="true">/</span><Link to="/engagements/eng-001/agent" className="font-semibold text-brand-secondary hover:underline">Return to AI Agent</Link></nav>}
    {ai ? <>
      <Card title="Choose the right capability"><dl data-setup="capabilities" className="space-y-4 text-sm"><div><dt className="font-semibold text-primary">AI Agent</dt><dd className="mt-1 text-secondary">An assessment session with retained transcript and policy checks. This example reviews existing evidence only.</dd></div><div><dt className="font-semibold text-primary">AI Triage</dt><dd className="mt-1 text-secondary">Finding proposals, independent verification and a human decision. Continue to AI Review after this chapter.</dd></div><div><dt className="font-semibold text-primary">Fleet Agent</dt><dd className="mt-1 text-secondary">Host inventory and runtime telemetry. It is enrolled separately in Runtime Security.</dd></div></dl></Card>
      <Card title="Deployment configuration"><div data-setup="configuration" className="space-y-4 text-sm"><p className="text-secondary">An administrator supplies provider identity, an approved model and a write-only credential through deployment configuration. No real credential is needed here.</p><dl className="grid gap-4 sm:grid-cols-2">{[['Provider', 'openai-compatible (example)'], ['Model', 'Approved deployment model'], ['Credential', 'Secret manager reference · never browser storage'], ['Review policy', 'Manual human review'], ['Evidence scope', 'Recorded assessment only'], ['Budget and timeout', 'Bounded by deployment policy']].map(([label, value]) => <div key={label} data-setup-field={label}><dt className="text-xs text-tertiary">{label}</dt><dd className="mt-1 font-medium text-primary">{value}</dd></div>)}</dl><p className="rounded-lg border border-secondary bg-secondary p-3 text-secondary">Configuration names: <code>SYNAPSE_LLM_PROVIDER</code>, <code>SYNAPSE_LLM_MODEL</code> and <code>SYNAPSE_LLM_API_KEY</code>. The console reports readiness; these values are configured by the deployment administrator.</p></div></Card>
      <Card title="Readiness checkpoint"><p data-setup="ready" className="text-sm text-secondary">{s.aiReady ? 'Ready · The simulated configuration check passed. Continue to the retained-evidence review.' : 'Blocked · Provider configuration is missing in this training scenario. The guide will record a simulated readiness check after you review the prerequisites.'}</p></Card>
    </> : <>
      <Card title="Two connections, different responsibilities"><dl data-setup="connections" className="space-y-4 text-sm"><div><dt className="font-semibold text-primary">Source-control connector</dt><dd className="mt-1 text-secondary">Read access to a private repository. Host matching selects the credential at acquisition time; it does not subscribe to repository events.</dd></div><div><dt className="font-semibold text-primary">CI/CD integration</dt><dd className="mt-1 text-secondary">Jenkins and Azure Pipelines read existing builds. GitHub, GitLab and Bitbucket receive inbound repository events. Polling does not start a pipeline.</dd></div></dl></Card>
      <Card title="GitHub deployment handoff"><div data-setup="webhook" className="space-y-3 text-sm text-secondary"><p>Bind the connection to one Git-backed Project. An administrator enables inbound webhooks in the deployment and provisions a write-only webhook secret through the integration API.</p><p>Configure the repository webhook with the returned public hook URL, the same secret, and push / pull request events. This is a deployment handoff; the current console does not provide a GitHub provisioning form.</p><p>Delivery uses the bound Project and exact commit. Duplicate deliveries are deduplicated. The repository event cannot redirect the scan to a different Project.</p><p className="font-medium text-primary">{s.webhookReady ? 'Simulated webhook provisioned · /api/v1/hooks/demo-github' : 'Webhook not provisioned in this scenario'}</p></div></Card>
      <Card title="Recorded delivery"><div data-setup="delivery" className="space-y-3 text-sm text-secondary">{s.eventAt ? <><p className="font-semibold text-success-primary">Delivery demo-pr-42 recorded</p><dl className="grid gap-4 sm:grid-cols-2">{[['Repository', 'Synapse CE · GitHub'], ['Commit', 'a1b2c3d'], ['Analysis', 'an-001'], ['Quality gate', 'Failed · new Critical issues require review'], ['PR feedback', 'Synthetic check: changes required'], ['Recorded', new Date(s.eventAt).toLocaleString()]].map(([key, value]) => <div key={key}><dt className="text-xs text-tertiary">{key}</dt><dd className="mt-1 text-primary">{value}</dd></div>)}</dl><p>The build can succeed while the quality gate fails. Continue to Quality Policies & CI to attach coverage and evaluate an improved revision.</p></> : <p>After binding and enabling the inbound connection, Next records a synthetic PR delivery and its existing analysis result. No repository or pipeline is contacted.</p>}</div></Card>
    </>}
    {s.storageWarning && <p role="alert" className="text-sm text-warning-primary">Browser storage is unavailable. Keep this tab open; progress cannot survive a reload.</p>}
  </div>
}
