import { DEMO_ISSUES, DEMO_PACKAGES, SEVERITY_RISK } from '../scenario/catalog'
import { actionWire, advisoryWire, occurrenceWire, closureManifest, closurePreview, comparisonItems, comparisonWire, cycleWire, inComparisonScope, members, snapshotWire, sourceWire, syncWire } from '../scenario/data'
import { COMPARISON_ID, INITIAL_ID, RETEST_ID, retest } from '../scenario/store'
import { analysis, overview, project } from '../workflows/data'
import { QUALITY_ISSUES, counts } from '../workflows/catalog'
import { type QualityAnalysis } from '../workflows/store'
import { ADDED_FINDING_INDICES, GATE_KEY, PROFILE_KEY, type IntelligenceState, type IntelRun, type PolicyState, type RemediationState } from './store'

export const VERIFIED_ID = 'learn-checkout-verification'
export const VERIFIED_COMPARISON = 'learn-checkout-verified-comparison'
export const teams = ['Platform Engineering', 'Application Security'].map((name, i) => ({ id: i ? 'team-security' : 'team-platform', name, slug: i ? 'application-security' : 'platform-engineering', archived: false, revision: 1, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' }))
export function resolution(r: RemediationState) { return { resolution: 'resolved' as const, reason: r.assignment.mode === 'auto' ? 'codeowners_match' : 'manual_assignment', team_id: r.assignment.team_id, candidates: [r.assignment.team_id!], evidence: [{ path: DEMO_ISSUES[0].location.split(':')[0], line: 1, pattern: 'services/**', owners: ['@platform-engineering'], reason: 'Recorded CODEOWNERS route' }], policy_hash: 'demo-routing-policy', snapshot_hash: 'demo-routing-snapshot', input_hash: 'demo-routing-input' } }
export function ownershipCurrent(r: RemediationState) { return { assignment: r.assignment, finding_version: r.findingVersion, finding_assignee: r.assignment.assignee_id || '', resolution: 'resolved', reason: resolution(r).reason, updated_at: r.history.at(-1)?.created_at ?? r.scenario.asset!.created_at } }
export function verifiedAssessment(r: RemediationState) { const a = structuredClone(retest(r.scenario)!); a.id = VERIFIED_ID; a.name = 'Checkout API · Coverage verification'; a.createdAt = r.verificationAt!; a.snapshotAt = r.verificationAt; a.scan!.ref = 'verified'; a.scan!.finishedAt = r.verificationAt; a.findings = structuredClone(retest(r.scenario)!.findings); return a }
export function remediationSnapshot(r: RemediationState, assessmentId: string) {
  const a = assessmentId === VERIFIED_ID ? verifiedAssessment(r) : r.scenario.assessments.find(a => a.id === assessmentId)!
  const wire = snapshotWire(a, r.scenario)
  if (assessmentId === RETEST_ID) wire.dimensions = wire.dimensions.map(d => ['iac', 'licenses'].includes(d.producer) ? { ...d, state: 'partial', reason_code: 'demo_missing_iac_license_lanes' } : d)
  return wire
}
export function remediationItems(r: RemediationState, verified = false) {
  const baseline = comparisonItems(r.scenario).map((row, i) => {
    if (i < 10 || verified && i >= 14) return row
    if (i < 14) return { ...row, current_observation_id: `${row.identity_id}-retest`, current_observation: { ...row.baseline_observation, observed_at: verified ? r.verificationAt : retest(r.scenario)!.snapshotAt }, presence: 'still_detected', current_actionable: true, current_risk_milli: row.baseline_risk_milli, verification_state: 'detected', fixed_basis: '' }
    return { ...row, presence: 'not_evaluated', coverage_decision: 'not_comparable', comparable_baseline: false, verification_state: 'unknown', fixed_basis: '', current_risk_milli: row.baseline_risk_milli }
  })
  const added = ADDED_FINDING_INDICES.map((i, n) => { const source = baseline[i]; return { ...source, id: `learn-new-diff-${n}`, position: baseline.length + n, identity_id: `learn-added-${i + 1}`, baseline_observation_id: '', baseline_observation: null, current_observation_id: `learn-new-observation-${n}`, current_observation: { ...source.baseline_observation!, observed_at: verified ? r.verificationAt : retest(r.scenario)!.snapshotAt }, presence: 'new', baseline_actionable: false, current_actionable: true, baseline_risk_milli: 0, current_risk_milli: SEVERITY_RISK[DEMO_ISSUES[i].severity] * 1000, verification_state: 'detected', fixed_basis: '' } })
  return [...baseline, ...added]
}
export function remediationSummary(r: RemediationState, verified = false, scope: string | null = 'all') {
  const items = remediationItems(r, verified).filter(i => inComparisonScope(i.finding_kind, scope))
  const baseline = items.filter(i => i.baseline_observation), current = items.filter(i => i.current_observation)
  const fixed = items.filter(i => i.presence === 'not_detected_under_comparable_coverage'), risk = baseline.reduce((sum, i) => sum + i.baseline_risk_milli, 0), currentRisk = current.reduce((sum, i) => sum + i.current_risk_milli, 0)
  return { comparison_id: verified ? VERIFIED_COMPARISON : COMPARISON_ID, baseline_snapshot_id: `${INITIAL_ID}-snapshot-1`, current_snapshot_id: `${verified ? VERIFIED_ID : RETEST_ID}-snapshot-1`, risk_model_version: 1, fixed_rate: { numerator: fixed.length, denominator: baseline.filter(i => i.comparable_baseline).length }, count_reduction: { numerator: baseline.length - current.length, denominator: baseline.length }, risk_reduction: { numerator: risk - currentRisk, denominator: risk }, baseline_count: baseline.length, current_count: current.length, fixed_count: fixed.length, still_detected_count: items.filter(i => i.presence === 'still_detected').length, new_count: items.filter(i => i.presence === 'new').length, not_evaluated_count: items.filter(i => i.presence === 'not_evaluated').length, reopened_count: 0, review_count: 0, baseline_risk: risk, current_risk: currentRisk, new_risk: items.filter(i => i.presence === 'new').reduce((sum, i) => sum + i.current_risk_milli, 0), reopened_risk: 0, baseline_severity: counts(baseline.map(i => ({ severity: i.baseline_observation!.severity })), 'severity'), current_severity: counts(current.map(i => ({ severity: i.current_observation!.severity })), 'severity') }
}
export function remediationComparison(r: RemediationState, verified = false) { return { ...comparisonWire(r.scenario), id: verified ? VERIFIED_COMPARISON : COMPARISON_ID, ...remediationSummary(r, verified), summary: remediationSummary(r, verified), created_at: verified ? r.verificationAt : r.scenario.comparisonAt, completed_at: verified ? r.verificationAt : r.scenario.comparisonAt } }
export function remediationCycle(r: RemediationState) { return { ...cycleWire(r.scenario), selected_head_assessment_id: r.verificationAt ? VERIFIED_ID : RETEST_ID, next_retest_number: r.verificationAt ? 3 : 2, version: r.scenario.closure ? 4 : r.verificationAt ? 3 : 2 } }
export function remediationMembers(r: RemediationState) { return [...members(r.scenario), ...(r.verificationAt ? [{ ...members(r.scenario)[1], assessment_id: VERIFIED_ID, predecessor_assessment_id: RETEST_ID, retest_number: 2, created_at: r.verificationAt }] : [])] }
export function remediationPreview(r: RemediationState) {
  const base = closurePreview(r.scenario), coverage = !r.verificationAt
  const accepted = r.overrideIds.includes('release:retained-findings') && Boolean(r.overrideReason.trim())
  return { ...base, cycle_version: remediationCycle(r).version, final_assessment_id: r.verificationAt ? VERIFIED_ID : RETEST_ID, final_snapshot_id: `${r.verificationAt ? VERIFIED_ID : RETEST_ID}-snapshot-1`, comparison_id: r.verificationAt ? VERIFIED_COMPARISON : COMPARISON_ID, path: remediationMembers(r).map((m, i) => ({ ...m, path_position: i, snapshot_id: `${m.assessment_id}-snapshot-1` })), policy: { ...base.policy, commit_allowed: !coverage && accepted, blockers: [...(coverage ? [{ id: 'coverage:missing-lane', code: 'coverage_incomplete', message: 'Four findings were not evaluated. Comparable coverage is required.', overrideable: false, overridden: false }] : []), { id: 'release:retained-findings', code: 'retained_findings', message: 'Seven detected findings require a recorded, time-limited release exception.', overrideable: true, overridden: accepted }], coverage_decisions: { initial: [], final: [{ snapshot_id: `${r.verificationAt ? VERIFIED_ID : RETEST_ID}-snapshot-1`, dimension_id: 'iac-and-licenses:repository', state: coverage ? 'partial' : 'complete', reason_code: coverage ? 'demo_missing_iac_license_lanes' : 'demo_comparable_verification', waived: false }] } }, references: accepted ? [{ kind: 'accepted_risk', id: 'demo-release-exception-7-days', lifecycle: 'active', expires_at: new Date(Date.parse(r.verificationAt!) + 7 * 86400000).toISOString() }] : [] }
}
export function remediationManifest(r: RemediationState) { return { ...closureManifest(r.scenario), ...remediationPreview(r), id: 'learn-checkout-closure', cycle_version: 4, override_blocker_ids: r.overrideIds, override_reason: r.overrideReason, coverage_decisions: remediationPreview(r).policy.coverage_decisions } }
export const INTEL_CASES = [{ id: 'DEMO-CHECKOUT-004', packageIndex: 3, score: 7.5, fixed: '2.0.1' }, { id: 'DEMO-ECOSYSTEM-1', packageIndex: 4, score: 9.8, fixed: '3.0.3' }, { id: 'DEMO-ECOSYSTEM-2', packageIndex: 7, score: 5.3, fixed: '1.4.4' }, { id: 'DEMO-ECOSYSTEM-3', packageIndex: 9, score: 3.1, fixed: '1.2.1' }]
export function intelAdvisories(i: IntelligenceState) { const base = advisoryWire(i.scenario); return i.reconciledAt ? INTEL_CASES.map(c => ({ ...base, canonical: { ...base.canonical, Advisory: { ...base.canonical.Advisory, ID: c.id, CVSSScore: c.score, Summary: `DEMO: new advisory for ${DEMO_PACKAGES[c.packageIndex].name}. Upgrade the retained version to ${c.fixed}.` } }, risk_priority: c.score >= 9 ? 1 : c.score >= 7 ? 2 : c.score >= 4 ? 3 : 4, risk_score: c.score, sync_run_ids: i.runs.filter(r => r.mode === 'full' && r.state === 'succeeded').map(r => r.id) })) : [] }
export function intelOccurrences(i: IntelligenceState, advisoryId: string) { const c = INTEL_CASES.find(c => c.id === advisoryId); if (!i.reconciledAt || !c) return []; const p = DEMO_PACKAGES[c.packageIndex]; return [{ ...occurrenceWire(i.scenario), ID: c.id === 'DEMO-CHECKOUT-004' ? 'learn-token-occurrence' : `learn-occurrence-${c.packageIndex}`, AdvisoryID: c.id, ComponentID: p.name, ComponentFingerprint: `pkg:${p.ecosystem}/${p.name}@${p.fixed}`, Ecosystem: p.ecosystem, Package: p.name, ComponentVersion: p.fixed, FixedVersion: c.fixed }] }
export function intelActions(i: IntelligenceState) {
  if (!i.reconciledAt) return []
  const base = actionWire(i.scenario)
  return INTEL_CASES.map(c => {
    const occurrence = intelOccurrences(i, c.id)[0]
    return { ...base, id: `learn-risk-action-${c.packageIndex}`, occurrence_id: occurrence.ID, title: `DEMO: assess ${occurrence.Package}@${occurrence.ComponentVersion} and plan remediation` }
  })
}
export function intelRunWire(r: IntelRun, i: IntelligenceState) { const s = i.scenario, complete = r.state === 'succeeded', first = i.runs.find(run => run.sourceId === 'learn-source' && run.mode === 'full' && run.state === 'succeeded')?.id === r.id, inserted = complete && first ? 4 : 0; return { ...syncWire({ ...r, feedPublished: r.mode === 'full' }, s), source_id: r.sourceId, state: r.state, counts: { processed: complete ? 4 : 0, inserted, updated: 0, unchanged: complete ? 4 - inserted : 0, skipped: 0, quarantined: 0 }, affected_revisions: inserted ? INTEL_CASES.map(c => ({ advisory_id: c.id, revision: 1, changed_at: r.finishedAt })) : [], error_samples: r.state === 'failed' ? ['demo_provider_timeout: Synthetic provider timeout. No network request was made.'] : [] } }
export function intelSources(i: IntelligenceState) { return ['learn-source', 'learn-osv-secondary'].map((id, n) => { const rows = i.runs.filter(r => r.sourceId === id), last = rows.at(-1), success = [...rows].reverse().find(r => r.state === 'succeeded'); return { ...sourceWire(i.scenario), id, key: n ? 'checkout-ecosystems' : 'checkout-osv', name: n ? 'Checkout ecosystem feed' : 'Checkout OSV feed', endpoint: n ? 'https://checkout.example/ecosystems.json' : i.scenario.source!.endpoint, health: { state: last?.state === 'failed' ? 'failed' : success ? 'healthy' : 'stale', stale: !success, latest_run: last ? intelRunWire(last, i) : null, last_successful_at: success?.finishedAt ?? new Date(Date.parse(i.scenario.source!.created_at) - 86400000).toISOString(), fresh_until: success?.finishedAt ? new Date(Date.parse(success.finishedAt) + 7200000).toISOString() : new Date(Date.parse(i.scenario.source!.created_at) - 79200000).toISOString() } } }) }
export const gateConditions = [{ metric: 'new_critical', op: '<=' as const, threshold: 0 }, { metric: 'coverage', op: '>=' as const, threshold: 85 }, { metric: 'duplication_density', op: '<=' as const, threshold: 3 }]
export function policyProfiles(p: PolicyState) { return ['typescript', 'go', 'python', 'java', 'javascript'].map((language, i) => ({ key: `default-${language}`, name: `Synapse Way · ${language}`, language, built_in: true, parent: '', activated_rules: Object.fromEntries(QUALITY_ISSUES.filter(r => r.language === language).map(r => [`${language}:checkout-${QUALITY_ISSUES.indexOf(r) + 1}`, { severity: r.severity }])), order: i })).concat(p.profileCopied ? [{ key: PROFILE_KEY, name: 'Checkout TypeScript', language: 'typescript', built_in: false, parent: 'default-typescript', activated_rules: { 'typescript:checkout-1': { severity: p.ruleSeverity }, 'typescript:checkout-9': { severity: 'info' } }, order: -1 }] : []) }
export function policyAnalysis(p: PolicyState, a: QualityAnalysis) {
  const improved = a.ref === 'improved', wire = analysis(a), custom = improved && p.gate
  const conditions = custom ? custom.conditions : wire.gate.results.map(c => ({ metric: c.metric, op: c.op, threshold: c.threshold }))
  const values: Record<string, number> = { new_critical: improved ? 0 : counts(QUALITY_ISSUES, 'severity').critical, coverage: improved ? 86 : 64, duplication_density: improved ? 1 : 5 }
  const results = conditions.map(c => ({ ...c, actual: values[c.metric], passed: c.op === '>=' ? values[c.metric] >= c.threshold : values[c.metric] <= c.threshold }))
  return { ...wire, origin: improved ? 'ci' : 'server', source_ref: improved ? 'refs/pull/42/head' : 'refs/heads/main',
    ci: improved ? { provider: 'github', run_id: 'demo-checkout-42', branch: 'improved', target_branch: 'main', actor: 'demo-ci', run_url: 'https://checkout.example/ci/runs/42', pull_request: '42' } : null,
    rating: { ...wire.rating, lines_of_code: 1000, tech_debt_minutes: improved ? 0 : 210, debt_ratio_pct: improved ? 0 : 3.5 },
    delta: improved ? { issues: { total: -QUALITY_ISSUES.length }, measures: { coverage: 22, duplicated_lines_density: -4 }, ratings: {} } : null,
    gate: { passed: results.every(r => r.passed), results }, gate_info: { key: custom ? GATE_KEY : 'default', name: custom ? custom.name : 'Synapse Way', source: custom ? 'managed' : 'default' } }
}
export function policyProject(p: PolicyState) { const wire = project(p.quality)!; const latest = [...p.quality.analyses].reverse().find(a => a.finishedAt); return { ...wire, decorate_pull_requests: p.decoration, default_profile_by_lang: Object.fromEntries(policyProfiles(p).filter(v => v.built_in).map(v => [v.language, v.language === 'typescript' && p.profileAssigned ? PROFILE_KEY : v.key])), latest_analysis: latest ? { ...policyAnalysis(p, latest), gate_passed: policyAnalysis(p, latest).gate.passed, new_issues: latest.ref === 'improved' ? 0 : QUALITY_ISSUES.length } : null } }
export function policyOverview(p: PolicyState, branch = '') { const wire = overview(p.quality, branch), a = [...p.quality.analyses].reverse().find(a => a.finishedAt && (!branch || a.ref === branch)); if (!a) return wire; const result = policyAnalysis(p, a); return { ...wire, latest_analysis: { ...wire.latest_analysis!, source_ref: result.source_ref }, gate: { status: result.gate.passed ? 'passed' : 'failed', ...result.gate_info, failed_conditions: result.gate.results.filter(c => !c.passed).map(c => ({ ...c, operator: c.op })) } } }
