import { AI_SETUP_STEPS, CI_SETUP_STEPS } from '../setup/steps'
import { findGuideTarget, type GuideAction, type GuideTarget } from '../guided-actions'
import { COMPARISON_ID, CYCLE_ID, DEMO_ADVISORY, INITIAL_ID, RETEST_ID } from '../scenario/store'
import { PROJECT_KEY } from '../workflows/store'
import { QUALITY_ISSUES } from '../workflows/catalog'
import { CLOSURE_REASON, GATE_KEY, OVERRIDE_REASON, PROFILE_KEY, type AdvancedMode, type AdvancedState } from './store'
import { VERIFIED_COMPARISON, VERIFIED_ID } from './data'

export const ADVANCED_NAMES: Record<AdvancedMode, string> = { 'ai-setup': 'AI Setup & Readiness', 'ci-setup': 'Repository & CI/CD Setup', remediation: 'Remediation & Ownership', intelligence: 'Intelligence Operations', policy: 'Quality Policies & CI' }
export interface AdvancedStep extends GuideAction<AdvancedState> { chapter: string; route: string; perform?: { path: string; body?: Record<string, string>; method?: 'POST' | 'PUT' }; finish?: boolean; form?: 'agent-review' | 'source-connector' | 'jenkins' | 'github' | 'pipeline-binding' | 'inbound-binding' | 'ownership-assign' | 'ownership-transfer' | 'closure' | 'profile' | 'gate' }
const t = (kind: GuideTarget['kind'], name: string): GuideTarget => ({ kind, name })
const sel = (name: string) => t('selector', name)
const read = (chapter: string, route: string, title: string, target: GuideTarget, body: string, why: string, check: AdvancedStep['done'] = () => true): AdvancedStep => ({ chapter, route, title, target, body, why, done: (s, doc) => Boolean(findGuideTarget(target, doc)) && check(s, doc) })
const field = (chapter: string, route: string, name: string, value: string, why: string, form?: AdvancedStep['form'], choice = false, target = t('field', name)): AdvancedStep => ({ chapter, route, title: name, target, form, example: choice ? { choice: value } : { value }, body: 'Review the highlighted example, then select Next.', why, done: (_, doc) => { const el = findGuideTarget(target, doc); return el instanceof HTMLInputElement || el instanceof HTMLSelectElement || el instanceof HTMLTextAreaElement ? el.value === value : el?.textContent?.trim().toLowerCase().startsWith(value.toLowerCase()) === true } })
const click = (chapter: string, route: string, name: string, why: string, done: AdvancedStep['done'], form?: AdvancedStep['form'], target = t('button', name)): AdvancedStep => ({ chapter, route, title: name, target, body: 'Select Next to perform the highlighted action.', why, done, form, auto: true })
const sim = (chapter: string, route: string, title: string, path: string, why: string, done: AdvancedStep['done'], body?: Record<string, string>): AdvancedStep => ({ chapter, route, title, target: sel('main'), body: 'Select Next to load the browser-local training event.', why, done, perform: { path, body } })
const finish = (mode: AdvancedMode, route: string, target: GuideTarget, why: string, done: AdvancedStep['done']): AdvancedStep => ({ ...read('Complete', route, `${ADVANCED_NAMES[mode]} complete`, target, 'Review the recorded outcome, then select Finish.', why, done), finish: true })
const owner = '/ownership', cycle = `/assessment-cycles/${CYCLE_ID}`, sources = '/vulnerability-intelligence?tab=sources', runs = '/vulnerability-intelligence?tab=sync-runs', profiles = '/code-quality/profiles', gates = '/code-quality/gates', project = `/code-quality/projects/${PROJECT_KEY}`
export const mixedRoute = `/engagements/${RETEST_ID}/comparison?comparison_mode=lifecycle&comparison_id=${COMPARISON_ID}&comparison_scope=all&comparison_base_assessment=${INITIAL_ID}&comparison_baseline=${INITIAL_ID}-snapshot-1&comparison_current=${RETEST_ID}-snapshot-1`
export const verifiedRoute = `/engagements/${VERIFIED_ID}/comparison?comparison_mode=lifecycle&comparison_id=${VERIFIED_COMPARISON}&comparison_scope=all&comparison_base_assessment=${INITIAL_ID}&comparison_baseline=${INITIAL_ID}-snapshot-1&comparison_current=${VERIFIED_ID}-snapshot-1`
const compare = (id: string) => sel(`[data-comparison-result="${id}"][data-comparison-ready="true"]`)
export const COVERAGE_ARTIFACT = { name: 'checkout-demo.lcov', type: 'text/plain', content: `TN:Synapse synthetic coverage\nSF:src/checkout.ts\n${Array.from({ length: 1000 }, (_, i) => `DA:${i + 1},${i < 860 ? 1 : 0}`).join('\n')}\nLF:1000\nLH:860\nend_of_record\n` }

export const ADVANCED_STEPS: Record<AdvancedMode, AdvancedStep[]> = {
  'ai-setup': AI_SETUP_STEPS,
  'ci-setup': CI_SETUP_STEPS,
  remediation: [
    read('Ownership & SLA', owner, 'Start with the remediation queue', sel('main table'), 'Review 18 findings across five severity levels and five languages. Each row records team routing, SLA state and a remediation due date.', 'This chapter starts with retained scan results. Ownership coordinates work; it does not change detection evidence.'),
    click('Ownership & SLA', owner, 'View ownership', 'Inspect the first finding and its recorded CODEOWNERS route to Platform Engineering.', (_, doc) => Boolean(findGuideTarget(t('field', 'Ownership action'), doc))),
    field('Ownership & SLA', owner, 'Ownership action', 'assign', 'Assign a team and an eligible individual while retaining the routing evidence.', 'ownership-assign'),
    field('Ownership & SLA', owner, 'Destination team', 'team-platform', 'The team owns remediation responsibility and defines eligible assignees.', 'ownership-assign'),
    click('Ownership & SLA', owner, 'Admin User', 'Select an eligible member of Platform Engineering.', (_, doc) => doc.body.textContent?.includes('Selected: Admin User') === true, 'ownership-assign'),
    click('Ownership & SLA', owner, 'Apply ownership action', 'Save a versioned manual assignment. The SLA deadline remains visible in the queue.', s => s.remediation.history.length >= 1, 'ownership-assign'),
    click('Ownership & SLA', owner, 'Show ownership history', 'Review the actor, before/after assignment and routing evidence.', (_, doc) => Boolean(findGuideTarget(t('button', 'Hide history'), doc))),
    field('Ownership & SLA', owner, 'Ownership action', 'transfer', 'Transfer responsibility when a different team should coordinate the fix.', 'ownership-transfer'),
    field('Ownership & SLA', owner, 'Destination team', 'team-security', 'Application Security becomes the new owning team.', 'ownership-transfer'),
    { ...field('Ownership & SLA', owner, 'Clear the current assignee during transfer', '', 'Clear the prior individual so the new team can select an eligible assignee.', 'ownership-transfer'), example: { checked: true }, done: (_, doc) => findGuideTarget(t('field', 'Clear the current assignee during transfer'), doc) instanceof HTMLInputElement && (findGuideTarget(t('field', 'Clear the current assignee during transfer'), doc) as HTMLInputElement).checked },
    click('Ownership & SLA', owner, 'Apply ownership action', 'Save the transfer with manual protection and a second audit decision.', s => s.remediation.history.length >= 2, 'ownership-transfer'),
    sim('Comparable re-test', `/engagements/${RETEST_ID}/comparison?comparison_scope=all`, 'Compare the retained snapshots', '/assessment-comparisons', 'No scan setup is repeated. Compare the Initial snapshot with the already recorded Re-test.', s => Boolean(s.remediation.scenario.comparisonAt), { baseline_snapshot_id: `${INITIAL_ID}-snapshot-1`, current_snapshot_id: `${RETEST_ID}-snapshot-1`, mode: 'lifecycle' }),
    read('Comparable re-test', mixedRoute, 'Read all four outcomes', compare(COMPARISON_ID), '10 Fixed, 4 Still detected, 3 New and 4 Not evaluated. Inspect the counts and the retained observations.', 'Observed risk reduction does not resolve missing coverage. Fixed requires comparable coverage. Missing configuration and license evaluation leaves four findings Not evaluated; it cannot prove remediation.'),
    click('Closure policy', cycle, 'Review closure', 'Preview closure before authorizing it. The server policy identifies missing coverage and retained findings.', (_, doc) => Boolean(findGuideTarget(t('field', 'Closure reason'), doc))),
    field('Closure policy', cycle, 'Closure reason', CLOSURE_REASON, 'The reason becomes part of the immutable closure record.', 'closure'),
    click('Closure policy', cycle, 'Preview server policy', 'Review the hard coverage blocker. A release exception cannot substitute for comparable scan evidence.', s => Boolean(s.remediation.scenario.preview), 'closure'),
    read('Closure policy', cycle, 'Review the coverage blocker', t('text', 'Closure policy'), 'Four findings were not evaluated. Closing remains disabled while this coverage blocker is active.', 'A hard blocker must be resolved with evidence before a policy-approved exception can be considered.', s => Boolean(s.remediation.scenario.preview) && !s.remediation.verificationAt),
    sim('Comparable re-test', cycle, 'Record comparable follow-up verification', '/playground/remediation/verify', 'A separate synthetic assessment restores the missing lanes. The original comparison remains immutable and still shows four Not evaluated findings.', s => Boolean(s.remediation.verificationAt)),
    read('Comparable re-test', verifiedRoute, 'Verify the new comparison', compare(VERIFIED_COMPARISON), 'The follow-up records 14 Fixed, 4 Still detected, 3 New and zero Not evaluated.', 'Seven detected findings remain open. Comparable coverage resolves uncertainty; it does not automatically accept remaining risk.'),
    click('Release exception', cycle, 'Review closure', 'Return to closure and review the now-comparable final assessment.', (_, doc) => Boolean(findGuideTarget(t('field', 'Closure reason'), doc))),
    { ...click('Release exception', cycle, 'Preview server policy', 'Review the retained-findings blocker under complete coverage.', (_, doc) => Boolean(findGuideTarget(t('field', 'Override'), doc)), 'closure'), prefill: [{ target: t('field', 'Closure reason'), example: { value: CLOSURE_REASON } }] },
    { ...field('Release exception', cycle, 'Override', '', 'Select the policy-approved release exception. Detection results remain unchanged.', 'closure'), example: { checked: true }, done: (_, doc) => (findGuideTarget(t('field', 'Override'), doc) as HTMLInputElement | null)?.checked === true },
    field('Release exception', cycle, 'Override reason', OVERRIDE_REASON, 'Record the responsible team, seven retained findings and the seven-day review window.', 'closure'),
    click('Release exception', cycle, 'Preview server policy', 'Request a fresh authoritative preview after changing the exception and rationale.', s => Boolean(s.remediation.overrideReason) && s.remediation.overrideIds.length === 1, 'closure'),
    click('Release exception', cycle, 'Close from authoritative preview', 'Seal the recorded policy decision, evidence pair and accepted-risk reference.', s => Boolean(s.remediation.scenario.closure), 'closure'),
    finish('remediation', cycle, sel('main'), 'The cycle is closed with complete verification coverage and a recorded release exception. Seven detected findings retain their remediation responsibility; the original mixed comparison remains available.', s => Boolean(s.remediation.scenario.closure) && s.remediation.history.length >= 2 && Boolean(s.remediation.verificationAt)),
  ],
  intelligence: [
    read('Feed health', sources, 'Review two configured intelligence feeds', sel('main'), 'Inspect the OSV and ecosystem feeds, their hourly cadence, two-hour stale threshold and last successful sync.', 'Freshness determines whether monitoring has current intelligence. Both simulated feeds begin stale; no provider is contacted.'),
    sim('Feed health', sources, 'Load a failed incremental run', '/playground/intelligence/failure', 'A recorded provider timeout demonstrates failure evidence without changing inventory or creating an exposure alert.', s => Boolean(s.intelligence.failureAt)),
    read('Recovery', runs, 'Inspect the failed sync', sel('main table'), 'Review Failed, the incremental mode and the synthetic provider-timeout error sample.', 'A failed sync does not prove that the feed is up to date or that newly disclosed vulnerabilities are absent.', s => Boolean(s.intelligence.failureAt)),
    sim('Recovery', sources, 'Retry with an incremental sync', '/vulnerability/sources/learn-source/sync', 'Incremental synchronization resumes from the feed checkpoint. The failed run remains in history.', s => s.intelligence.runs.some(r => r.state !== 'failed' && r.sourceId === 'learn-source'), { mode: 'incremental' }),
    read('Recovery', runs, 'Verify successful recovery', sel('main table'), 'Wait for the new Succeeded run and review its processed and unchanged counts.', 'Recovery needs a completed run; an accepted request alone is insufficient.', (s, doc) => Boolean(s.intelligence.recoveredAt) && [...doc.querySelectorAll('main tbody tr')].some(row => row.textContent?.includes('learn-intel-run-2') && row.textContent.toLowerCase().includes('succeeded'))),
    sim('Recovery', sources, 'Refresh the ecosystem feed', '/vulnerability/sources/learn-osv-secondary/sync', 'The second feed has its own checkpoint and freshness state. Refresh it independently.', s => s.intelligence.runs.some(r => r.sourceId === 'learn-osv-secondary'), { mode: 'incremental' }),
    read('Recovery', sources, 'Confirm both feeds are healthy', sel('main'), 'Both feeds now have a successful incremental run. Compare their separate freshness and checkpoint records.', 'A healthy primary feed does not make a stale secondary feed healthy.', s => s.intelligence.runs.some(r => r.sourceId === 'learn-osv-secondary' && r.state === 'succeeded')),
    read('Monitoring preferences', '/inbox', 'Review exposure notification preferences', sel('main'), 'Review the in-app preference for vulnerability actions before introducing the new advisory batch.', 'A preference controls delivery. Correlation and the retained exposure remain available independently of notification delivery.'),
    { ...field('Monitoring preferences', '/inbox', 'vulnerability_action.created in_app', 'enabled', 'Enable in-app delivery for the upcoming synthetic exposure. The preference uses its current revision.'), title: 'Enable in-app monitoring', done: s => s.intelligence.scenario.notificationPreference === 'enabled' },
    sim('Full reconciliation', sources, 'Reconcile a new advisory batch', '/vulnerability/sources/learn-source/sync', 'A full sync reconciles four synthetic advisories across npm, PyPI, Go and Maven inventory. The new batch contains Critical, High, Medium and Low risk.', s => s.intelligence.runs.some(r => r.sourceId === 'learn-source' && r.mode === 'full'), { mode: 'full' }),
    read('Full reconciliation', runs, 'Verify full-sync completion', sel('main table'), 'Wait for Succeeded and review the full run, four processed revisions and retained incremental history.', 'Full reconciliation records the new disclosure batch without running another code scan.', (s, doc) => Boolean(s.intelligence.reconciledAt) && [...doc.querySelectorAll('main tbody tr')].some(row => row.textContent?.includes('full') && row.textContent.toLowerCase().includes('succeeded'))),
    read('Exposure review', '/vulnerability-intelligence?tab=vulnerabilities', 'Review the advisory batch', sel('main table'), 'Review four advisories with distinct severities and ecosystem context. Continue with the Checkout token advisory.', 'Publication, ingestion and inventory correlation are separate checkpoints.'),
    read('Exposure review', `/vulnerability-intelligence/advisories/${DEMO_ADVISORY}`, 'Inspect the matched inventory', sel('main'), 'The High token advisory matches version 2.0.0 in the retained Checkout inventory. Review the fixed version, affected Asset and risk action.', 'An inventory match creates an exposure case. It does not establish runtime exploitability.'),
    read('Exposure review', `/vulnerability-intelligence/advisories/${DEMO_ADVISORY}`, 'Review exposure assessment history', t('button', 'checkout-token'), 'Review the assessment associated with the matched package occurrence.', 'The exposure history explains why this retained component is affected.'),
    click('Exposure review', `/vulnerability-intelligence/advisories/${DEMO_ADVISORY}`, 'checkout-token', 'Expand the retained risk assessment before reading the notification.', s => s.intelligence.scenario.monitorInvestigated),
    read('Notification outcome', '/inbox', 'Verify the delivered exposure alert', sel('main'), 'The in-app alert links to the matched advisory and Checkout Asset. Review the delivery time and unread state.', 'Delivery appears only after successful full reconciliation and an enabled notification preference.', s => Boolean(s.intelligence.scenario.notificationDeliveredAt)),
    sim('Notification outcome', '/inbox', 'Acknowledge the exposure alert', '/me/inbox/learn-monitor-message/read', 'Acknowledgement changes the Inbox read state. The underlying exposure remains open for remediation.', s => Boolean(s.intelligence.scenario.notificationReadAt)),
    finish('intelligence', '/inbox', sel('main'), 'Both feeds are healthy, the failed run remains auditable, the full batch is correlated and the delivered exposure alert is acknowledged.', s => Boolean(s.intelligence.reconciledAt && s.intelligence.scenario.notificationReadAt)),
  ],
  policy: [
    read('Quality profiles', profiles, 'Start with language-specific policies', sel('main'), 'Review profiles for TypeScript, Go, Python, Java and JavaScript. Rules carry all five severity levels.', 'Profiles define active rules and severity overrides. Quality Gates evaluate measured release criteria.'),
    click('Quality profiles', profiles, 'Synapse Way · typescript', 'Select the TypeScript baseline before making a custom copy.', (_, doc) => findGuideTarget(t('button', 'Synapse Way · typescript'), doc)?.getAttribute('aria-pressed') === 'true'),
    click('Quality profiles', profiles, 'Copy profile', 'Keep the managed baseline and create a project-specific profile.', (_, doc) => Boolean(doc.querySelector('#copy-key'))),
    field('Quality profiles', profiles, 'New Profile Key', PROFILE_KEY, 'A stable key identifies the custom profile.', 'profile', false, sel('#copy-key')),
    field('Quality profiles', profiles, 'Profile Display Name', 'Checkout TypeScript', 'The display name helps reviewers recognize the project policy.', 'profile'),
    click('Quality profiles', profiles, 'Create copy', 'Save a custom profile with its baseline parent and activated rules.', s => s.policy.profileCopied, 'profile'),
    click('Quality profiles', profiles, 'Checkout TypeScript', 'Review the custom profile before overriding severity.', (_, doc) => findGuideTarget(t('button', 'Checkout TypeScript'), doc)?.getAttribute('aria-pressed') === 'true'),
    { ...field('Quality profiles', profiles, `Severity for ${QUALITY_ISSUES[0].title}`, 'High', 'Raise the reviewed TypeScript rule to High. The baseline analysis remains a retained historical result.', undefined, true), done: s => s.policy.ruleSeverity === 'high' },
    { ...sim('Quality profiles', profiles, 'Assign the custom project profile', '/projects/checkout-quality/profiles/typescript', 'Assign the custom TypeScript rules to future Checkout analyses. Profiles for the other four languages remain distinct.', s => s.policy.profileAssigned), perform: { path: '/projects/checkout-quality/profiles/typescript', method: 'PUT', body: { profile: PROFILE_KEY } } },
    click('Release gate', gates, 'New gate', 'Create a custom release policy with three explicit criteria.', (_, doc) => Boolean(doc.querySelector('#gate-key'))),
    field('Release gate', gates, 'Name', 'Checkout Release', 'The gate name describes the release policy.', 'gate'),
    field('Release gate', gates, 'Key', GATE_KEY, 'The key identifies the immutable gate assignment.', 'gate', false, sel('#gate-key')),
    read('Release gate', gates, 'Review all three release conditions', sel('[role="dialog"] form'), 'Require zero new Critical issues, at least 85% coverage and at most 3% duplication. All condition values are filled automatically.', 'A gate fails when any measured condition fails. Unknown or unmeasured evidence must not be rendered as passing.', (_, doc) => ['New critical issues', 'Line coverage', 'Duplication density'].every((name, i) => doc.querySelector(`#gate-metric-${i}`)?.textContent?.trim() === name && doc.querySelector(`#gate-op-${i}`)?.textContent?.trim() === (i === 1 ? '>=' : '<=') && doc.querySelector<HTMLInputElement>(`#gate-threshold-${i}`)?.value === ['0', '85', '3'][i])),
    click('Release gate', gates, 'Create gate', 'Persist the three conditions before assigning this gate to the project.', s => Boolean(s.policy.gate), 'gate'),
    { ...field('Release gate', project, 'Quality gate', 'Checkout Release', 'Assign the custom gate to future project analyses.', undefined, true), done: s => s.policy.quality.project?.gateId === GATE_KEY },
    { ...field('CI integration', project, 'PR decoration', '', 'Enable policy reporting for the recorded pull-request analysis. This demo contacts no SCM provider.'), example: { checked: true }, done: s => s.policy.decoration },
    { ...read('CI integration', project, 'Attach the synthetic coverage artifact', sel('label:has(input[type="file"])'), 'The supplied LCOV artifact records 860 covered lines out of 1,000. No typing or file selection is required.', 'Coverage is evidence from the test pipeline. It is separate from the source scanner.'), prefill: [{ target: t('field', 'Coverage report (optional)'), example: { file: COVERAGE_ARTIFACT } }], done: (_, doc) => Boolean(doc.querySelector<HTMLInputElement>('input[type="file"]')?.files?.[0]?.name === COVERAGE_ARTIFACT.name) },
    click('CI integration', project, 'Run analysis', 'Record the synthetic CI result for PR #42 with the coverage artifact, custom profile and release gate.', s => Boolean(s.policy.ciImportedAt)),
    read('CI integration', `${project}/analysis?branch=improved`, 'Verify the PR analysis and gate', sel('[data-quality-analysis="learn-quality-analysis-improved"]'), 'Wait for the recorded CI result: zero new Critical issues, 86% coverage and 1% duplication. The three release conditions pass.', 'The CI provider, PR reference and policy provenance explain how this result was produced.', s => Boolean(s.policy.quality.analyses[1]?.finishedAt)),
    read('Policy comparison', `${project}/compare?base=main&head=improved`, 'Compare evidence and policy provenance', sel('[data-quality-base="learn-quality-analysis-main"][data-quality-head="learn-quality-analysis-improved"]'), 'Review 10 baseline issues → zero new issues, coverage 64% → 86% and duplication 5% → 1%.', 'The baseline used Synapse Way; the CI revision used Checkout Release. Review both measured improvement and the changed policy before drawing conclusions.'),
    finish('policy', `${project}/compare?base=main&head=improved`, sel('[data-quality-base="learn-quality-analysis-main"][data-quality-head="learn-quality-analysis-improved"]'), 'The project retains its original baseline, a custom TypeScript profile, three release criteria and a passing synthetic CI result with PR decoration enabled.', s => Boolean(s.policy.quality.analyses[1]?.finishedAt) && s.policy.coverageImported && s.policy.ruleSeverity === 'high'),
  ],
}
export function advancedRoute(mode: AdvancedMode, s: AdvancedState) { return ADVANCED_STEPS[mode][Math.min(s[mode].step, ADVANCED_STEPS[mode].length - 1)].route }
