import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

let registrations: ReturnType<typeof vi.spyOn>
beforeEach(() => {
  localStorage.clear()
  sessionStorage.clear()
  vi.resetModules()
  registrations = vi.spyOn(window, 'addEventListener')
})
afterEach(() => {
  for (const [type, listener] of registrations.mock.calls) {
    if (type === 'storage') window.removeEventListener(type, listener as EventListener)
  }
  vi.restoreAllMocks()
})

describe('Shared progress with tab-local chapter selection', () => {
  it('merges advanced chapter progress across stale tabs and resets only the selected chapter', async () => {
    const tabA = await import('./advanced/store')
    vi.resetModules()
    const tabB = await import('./advanced/store')
    tabA.updateAdvanced(s => { s.policy.step = 4; s.policy.completed = [0, 1, 2, 3]; s.policy.open = true })
    tabB.updateAdvanced(s => { s.intelligence.step = 2; s.intelligence.open = true })
    tabA.resetAdvanced('remediation')
    const saved = JSON.parse(localStorage.getItem(tabA.ADVANCED_KEY)!)
    expect(saved.policy.step).toBe(4)
    expect(saved.intelligence.step).toBe(2)
    window.dispatchEvent(new StorageEvent('storage', { key: tabA.ADVANCED_KEY }))
    expect(tabA.advancedStore.getSnapshot().policy.open).toBe(true)
    expect(tabB.advancedStore.getSnapshot().intelligence.open).toBe(true)
    expect(tabB.advancedStore.getSnapshot().policy.step).toBe(4)
  })
  it('preserves another chapter when a stale tab writes and when it resets its own chapter', async () => {
    const tabA = await import('./workflows/store')
    tabA.chooseMode('quality')
    vi.resetModules()
    const tabB = await import('./workflows/store')
    tabB.chooseMode('ai')
    tabA.updateWorkflows(s => { s.quality.step = 7; s.quality.completed = [0, 1, 2] })
    tabB.updateWorkflows(s => { s.ai.step = 4 })
    const saved = JSON.parse(localStorage.getItem(tabA.WORKFLOW_KEY)!)
    expect(saved.quality).toMatchObject({ step: 7, completed: [0, 1, 2] })
    expect(saved.ai.step).toBe(4)
    tabB.resetWorkflow('ai')
    expect(JSON.parse(localStorage.getItem(tabA.WORKFLOW_KEY)!).quality.step).toBe(7)
    window.dispatchEvent(new StorageEvent('storage', { key: tabA.WORKFLOW_KEY }))
    expect(tabA.workflowStore.getSnapshot().mode).toBe('quality')
    expect(tabB.workflowStore.getSnapshot().mode).toBe('ai')
    expect(tabA.workflowStore.getSnapshot().quality.open).toBe(true)
  })
  it('merges fresh scan checkpoints before a stale tab updates its view', async () => {
    const tabA = await import('./scenario/store')
    vi.resetModules()
    const tabB = await import('./scenario/store')
    tabA.updateScenario(s => { s.enabled = true; s.step = 9; s.completed = ['asset', 'scan']; s.feedPublished = true })
    tabB.updateScenario(s => { s.open = false })
    expect(JSON.parse(localStorage.getItem(tabA.SCENARIO_KEY)!)).toMatchObject({ step: 9, completed: ['asset', 'scan'], feedPublished: true })
    window.dispatchEvent(new StorageEvent('storage', { key: tabA.SCENARIO_KEY }))
    expect(tabA.scenarioStore.getSnapshot()).toMatchObject({ enabled: true, step: 9 })
    expect(tabB.scenarioStore.getSnapshot()).toMatchObject({ enabled: false, open: false, step: 9 })
  })
  it('restores the selected chapter from this tab rather than the shared dataset', async () => {
    const tabA = await import('./workflows/store')
    tabA.chooseMode('quality')
    const raw = JSON.parse(localStorage.getItem(tabA.WORKFLOW_KEY)!)
    localStorage.setItem(tabA.WORKFLOW_KEY, JSON.stringify({ ...raw, mode: 'ai' }))
    vi.resetModules()
    const refreshed = await import('./workflows/store')
    expect(refreshed.workflowStore.getSnapshot().mode).toBe('quality')
  })
  it('retains in-memory progress when browser storage is unavailable', async () => {
    const store = await import('./workflows/store')
    store.updateWorkflows(s => { s.quality.step = 3 })
    vi.spyOn(Storage.prototype, 'getItem').mockImplementation(() => { throw new Error('Storage blocked') })
    vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('Storage blocked') })
    store.updateWorkflows(s => { s.ai.step = 2 })
    expect(store.workflowStore.getSnapshot()).toMatchObject({ storageWarning: true, quality: { step: 3 }, ai: { step: 2 } })
  })
  it.each([false, true])('preserves consecutive writes when only setItem fails (existing data: %s)', async (persisted) => {
    const workflow = await import('./workflows/store')
    const scenario = await import('./scenario/store')
    const advanced = await import('./advanced/store')
    const setup = await import('./setup/store')
    if (persisted) {
      workflow.updateWorkflows(s => { s.quality.step = 3 })
      scenario.updateScenario(s => { s.step = 3 })
      advanced.updateAdvanced(s => { s.policy.step = 3 })
      setup.updateSetup(s => { s.aiReady = true })
    }
    const write = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('Quota exceeded', 'QuotaExceededError') })
    workflow.updateWorkflows(s => { s.quality.step = 4; s.quality.completed = [0, 1, 2] })
    scenario.updateScenario(s => { s.step = 4; s.completed = ['asset', 'engagement']; s.asset = advanced.seededScenario().asset })
    advanced.updateAdvanced(s => { s.policy.step = 4; s.policy.completed = [0, 1, 2] })
    setup.updateSetup(s => { s.aiReady = true })
    window.dispatchEvent(new StorageEvent('storage', { key: null }))
    workflow.updateWorkflows(s => { s.ai.step = 2 })
    scenario.updateScenario(s => { s.open = false })
    advanced.updateAdvanced(s => { s.intelligence.step = 2 })
    setup.updateSetup(s => { s.webhookReady = true })
    expect(workflow.workflowStore.getSnapshot()).toMatchObject({ storageWarning: true, quality: { step: 4, completed: [0, 1, 2] }, ai: { step: 2 } })
    expect(scenario.scenarioStore.getSnapshot()).toMatchObject({ storageWarning: true, step: 4, completed: ['asset', 'engagement'], asset: { key: 'checkout-api' } })
    expect(advanced.advancedStore.getSnapshot()).toMatchObject({ storageWarning: true, policy: { step: 4, completed: [0, 1, 2] }, intelligence: { step: 2 } })
    expect(setup.setupStore.getSnapshot()).toMatchObject({ storageWarning: true, aiReady: true, webhookReady: true })
    write.mockRestore()
    workflow.updateWorkflows(() => {})
    scenario.updateScenario(() => {})
    advanced.updateAdvanced(() => {})
    setup.updateSetup(() => {})
    for (const key of [workflow.WORKFLOW_KEY, scenario.SCENARIO_KEY, advanced.ADVANCED_KEY, setup.SETUP_KEY]) {
      expect(JSON.parse(localStorage.getItem(key)!).storageWarning).toBe(false)
    }
    expect(JSON.parse(localStorage.getItem(scenario.SCENARIO_KEY)!).asset.key).toBe('checkout-api')
  })
  it('resets only the malformed chapter in shared documents', async () => {
    const workflow = await import('./workflows/store')
    const advanced = await import('./advanced/store')
    const setup = await import('./setup/store')
    workflow.updateWorkflows(s => { s.overviewComplete = true; s.ai.step = 4; s.quality.issueStatus = 'removed-status' })
    advanced.updateAdvanced(s => { s.intelligence.step = 4; s['ci-setup'].step = 3; s.policy.ruleSeverity = 'removed-severity' })
    setup.updateSetup(s => { s.aiReady = true })
    const broken = JSON.parse(localStorage.getItem(setup.SETUP_KEY)!)
    broken.connections = [null]
    localStorage.setItem(setup.SETUP_KEY, JSON.stringify(broken))
    vi.resetModules()
    const restoredWorkflow = await import('./workflows/store')
    const restoredAdvanced = await import('./advanced/store')
    const restoredSetup = await import('./setup/store')
    expect(restoredWorkflow.workflowStore.getSnapshot()).toMatchObject({ overviewComplete: true, ai: { step: 4 }, quality: { step: 0, issueStatus: 'open' } })
    expect(restoredAdvanced.advancedStore.getSnapshot()).toMatchObject({ intelligence: { step: 4 }, 'ci-setup': { step: 3 }, policy: { step: 0, ruleSeverity: 'medium' } })
    expect(restoredSetup.setupStore.getSnapshot()).toMatchObject({ aiReady: true, connections: [] })
  })
  it('new tabs inherit the last chapter and its project while existing tabs keep their selection', async () => {
    const workflow = await import('./workflows/store')
    workflow.chooseMode('quality')
    workflow.updateWorkflows(s => { s.quality.step = 4; s.quality.project = { key: workflow.PROJECT_KEY, name: 'Checkout', source: workflow.PROJECT_TARGET, ref: 'main', gateId: 'default', createdAt: new Date().toISOString() } })
    sessionStorage.clear()
    vi.resetModules()
    const newTab = await import('./workflows/store')
    expect(newTab.workflowStore.getSnapshot()).toMatchObject({ mode: 'quality', quality: { open: true, step: 4, project: { key: workflow.PROJECT_KEY } } })
    newTab.chooseMode('ai')
    window.dispatchEvent(new StorageEvent('storage', { key: workflow.WORKFLOW_KEY }))
    expect(workflow.workflowStore.getSnapshot().mode).toBe('quality')
    expect(newTab.workflowStore.getSnapshot().mode).toBe('ai')
  })

  it('migrates the added finding out of the partial IaC lane without resetting remediation', async () => {
    const store = await import('./advanced/store')
    store.updateAdvanced(s => { s.remediation.step = 6; s.remediation.scenario.assessments[1].findings.find(f => f.id === 'learn-added-10')!.id = 'learn-added-15' })
    vi.resetModules()
    const restored = (await import('./advanced/store')).advancedStore.getSnapshot().remediation
    expect(restored.step).toBe(6)
    expect(restored.scenario.assessments[1].findings.map(f => f.id)).toContain('learn-added-10')
    expect(restored.scenario.assessments[1].findings.map(f => f.id)).not.toContain('learn-added-15')
  })

})
