import { findGuideTarget, type GuideAction, type GuideTarget } from '../guided-actions'
import { AI_TITLES } from './data'
import { AI_ENG, HOST_ID, INCIDENT_ID, PROJECT_KEY, PROJECT_TARGET, REVIEWER, RUNTIME_ENG, type WorkflowMode, type Workflows } from './store'

export const WORKFLOW_NAMES: Record<WorkflowMode, string> = { runtime: 'Runtime Security Walkthrough', ai: 'AI Review Walkthrough', quality: 'Code Quality Walkthrough' }
export interface WorkflowStep extends GuideAction<Workflows> { chapter: string; route: string; spotlight?: GuideTarget; perform?: { path: string; body?: Record<string, string> }; finish?: boolean }
const selector = (name: string): GuideTarget => ({ kind: 'selector', name })
const target = (kind: GuideTarget['kind'], name: string): GuideTarget => ({ kind, name })
const shown = (t: GuideTarget) => (_: Workflows, doc: Document) => Boolean(findGuideTarget(t, doc))
const read = (chapter: string, route: string, title: string, t: GuideTarget, body: string, why: string, done?: WorkflowStep['done']): WorkflowStep => ({ chapter, route, title, target: t, body, why, done: (s, doc) => shown(t)(s, doc) && (!done || done(s, doc)) })
const field = (chapter: string, route: string, name: string, value: string, why: string, choice = false): WorkflowStep => ({ chapter, route, title: name, target: target('field', name), example: choice ? { choice: value } : { value }, body: 'Review the highlighted example, then select Next.', why, done: (_, doc) => { const el = findGuideTarget(target('field', name), doc); return el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement || el instanceof HTMLSelectElement ? el.value === value : el?.textContent?.trim().toLowerCase().startsWith(value.toLowerCase()) === true } })
const click = (chapter: string, route: string, name: string, why: string, done: WorkflowStep['done'], t = target('button', name)): WorkflowStep => ({ chapter, route, title: name, target: t, body: 'Select Next to perform the highlighted action.', why, done, auto: true })
const simulation = (chapter: string, route: string, title: string, t: GuideTarget, path: string, why: string, done: WorkflowStep['done']): WorkflowStep => ({ chapter, route, title, target: t, body: 'Select Next to load this browser-local training event.', why, done, perform: { path } })
const finish = (mode: WorkflowMode, route: string, t: GuideTarget, why: string, done: WorkflowStep['done']): WorkflowStep => ({ ...read('Complete', route, `${WORKFLOW_NAMES[mode]} complete`, t, 'Review the outcome, then select Finish. Your demo data remains available for further exploration.', why, done), finish: true })
const eng = `/engagements/${RUNTIME_ENG}/detections`, inc = `/fleet/incidents/${INCIDENT_ID}`, res = '/blueteam/response', ai = '/ai-triage/reviews', findings = `/engagements/${AI_ENG}/findings`, quality = `/code-quality/projects/${PROJECT_KEY}`

export const WORKFLOW_STEPS: Record<WorkflowMode, WorkflowStep[]> = {
  runtime: [
    read('Agent enrolment', '/fleet/agents', 'Connect runtime visibility', target('text', 'Agent enrolment'), 'An enrolled agent supplies inventory and runtime telemetry for a scoped host.', 'This exercise uses a simulated agent. No installer, host connection or telemetry collection runs.'),
    field('Agent enrolment', '/fleet/agents', 'Enrolment token lifetime minutes', '15', 'A short-lived enrolment token limits the window for a new agent to join.'),
    click('Agent enrolment', '/fleet/agents', 'Mint token', 'The token is shown once. This training token cannot enrol a real agent.', s => Boolean(s.runtime.tokenAt)),
    simulation('Agent enrolment', '/fleet/agents', 'Simulate the first agent check-in', target('text', 'Agent enrolment'), '/playground/runtime/enroll', 'The demo consumes the enrolment checkpoint and registers checkout-demo-agent with scan.host and detect.runtime capabilities.', s => Boolean(s.runtime.enrolledAt)),
    read('Agent enrolment', '/fleet/agents', 'Verify the enrolled agent', selector('main [role="list"]'), 'Review checkout-demo-agent, its Healthy state, platform and last check-in.', 'Healthy check-in establishes availability. Coverage still requires recorded telemetry.', s => Boolean(s.runtime.enrolledAt)),
    simulation('Inventory & coverage', '/fleet/hosts', 'Record host and workload inventory', selector('main'), '/playground/runtime/telemetry', 'A synthetic batch records one host, six packages and three workloads and four sensor classes. The inventory covers Node.js, Python, Java and the Go session service.', s => Boolean(s.runtime.telemetryAt)),
    read('Inventory & coverage', '/fleet/hosts', 'Review the host inventory', selector('table, [role="table"]'), 'The checkout-demo host is associated with the training assessment.', 'Host inventory connects packages and runtime observations to a stable technical Asset.'),
    read('Inventory & coverage', '/fleet/workloads', 'Review the checkout workload', selector('main h2'), 'Review checkout-api, payment-worker and session-service, with their namespaces, service accounts and distinct image digests.', 'Workload identity gives a detection deployment context; an image digest identifies the recorded build.'),
    read('Inventory & coverage', '/fleet/coverage-windows', 'Validate telemetry coverage', selector('main'), 'Review Process, Network, File and Privilege coverage, with 96 samples across four batches and zero gaps.', 'Missing sensors reduce confidence in absence. Coverage does not lower the risk of an observed detection.'),
    simulation('Detection & incident', eng, 'Record synthetic detections', selector('#engagement-tabpanel'), '/playground/runtime/detect', 'Five training rules record File, Privilege, Network and Process events across Critical, High, Medium, Low and Info. The next steps investigate the High file-access case.', s => Boolean(s.runtime.detectedAt)),
    read('Detection & incident', eng, 'Review detection evidence', selector('#engagement-tabpanel'), 'Compare all five severity levels, sensor classes and observation counts. The file-access case has High severity and three observations on the scoped host.', 'A detection is an observed event. Correlation groups related events into an incident for investigation.'),
    click('Detection & incident', eng, 'Correlate', 'Correlation creates five distinct incidents. Continue with the High file-access incident; the other four remain available for separate investigation.', s => Boolean(s.runtime.incidentAt)),
    read('Detection & incident', inc, 'Assess risk, confidence and coverage', selector('[data-incident-id="learn-runtime-incident"]'), 'Review the incident and its separate Risk, Confidence and Coverage scores.', 'Risk describes escalation. Confidence describes evidence strength. Coverage describes telemetry completeness.'),
    { ...field('Detection & incident', inc, 'Change incident status', 'Investigating', 'Investigating records that an analyst is actively reviewing the incident.', true), done: s => s.runtime.incidentStatus === 'investigating' },
    { ...field('Detection & incident', inc, 'Set incident disposition', 'True positive', 'The analyst confirms the synthetic observation is relevant to this training case.', true), done: s => s.runtime.disposition === 'true_positive' },
    field('Detection & incident', inc, 'Assign owner', REVIEWER, 'The incident owner coordinates investigation and response.'),
    click('Detection & incident', inc, 'Assign', 'Save the owner before planning a response.', s => s.runtime.owner === REVIEWER),
    field('Detection & incident', inc, 'Add comment', 'Synthetic file-access evidence reviewed. Plan scoped isolation, verify the result and revert after validation.', 'Record the evidence and the planned response so another analyst can follow the decision.'),
    click('Detection & incident', inc, 'Comment', 'The saved note remains with the incident.', s => Boolean(s.runtime.comment)),
    field('Response', res, 'Target', HOST_ID, 'The response applies only to the scoped demo host. Keep Checkout Runtime selected and Isolate host as the action.'),
    click('Response', res, 'Plan (dry run)', 'A dry run shows the proposed steps and blast radius before approval or application.', s => Boolean(s.runtime.planAt)),
    read('Response', res, 'Review the response plan', selector('main ol'), 'Review the one-host scope and simulation verification step.', 'The plan executes nothing. Applying the demo records approval and evidence without changing a host.'),
    click('Response', res, 'Apply through the gate', 'The simulated admission gate retains the reviewer, verification result and evidence reference.', s => Boolean(s.runtime.appliedAt)),
    read('Response', res, 'Verify the applied response', selector('table, [role="table"]'), 'Review Applied, the approver and the verification result in the response ledger.', 'A response needs recorded verification; a successful request alone does not show its effect.'),
    { ...simulation('Response', res, 'Revert the simulated response', target('button', 'Revert'), '/blueteam/response/learn-response-1/revert', 'Reversal is retained as an audited response. This browser-local action changes no host.', s => Boolean(s.runtime.revertedAt)), perform: { path: '/blueteam/response/learn-response-1/revert', body: { target: HOST_ID } } },
    { ...field('Response', inc, 'Change incident status', 'Resolved', 'Resolve after reviewing the evidence, verification and reversal.', true), done: s => s.runtime.incidentStatus === 'resolved' },
    finish('runtime', '/fleet/incidents', selector('main table, main [role=table]'), 'The High file-access incident is Resolved after a verified, reverted response. Four incidents remain Open for separate investigation, spanning Critical, Medium, Low and Info.', s => Boolean(s.runtime.revertedAt) && s.runtime.incidentStatus === 'resolved'),
  ],
  ai: [
    read('AI proposals', ai, 'Start with human review', target('text', 'AI Triage Reviews'), 'AI proposals help prioritize review. The analyst retains responsibility for the decision.', 'This walkthrough loads five synthetic proposals and independent verifier results. No model or provider is called.'),
    simulation('AI proposals', ai, 'Load five review cases', selector('main'), '/playground/ai/proposals', 'Five proposals span TypeScript, Go, Python, Java and JavaScript, with all five severity levels. Review a test fixture and production code with conflicting verifier evidence; three additional cases remain available.', s => Boolean(s.ai.proposalsAt)),
    click('Human review', ai, 'Review the test fixture proposal', 'Read the proposer, verifier, confidence and policy reason before deciding.', shown(target('field', 'Mandatory rationale')), selector('[data-review-id="learn-review-1"]')),
    { ...click('Human review', ai, 'Claim review', 'Claiming establishes the responsible human reviewer and increments the review version.', s => s.ai.reviews[0].owner === REVIEWER), spotlight: selector('[data-ai-review-evidence]'), body: 'Read the model, policy and evidence details below the AI recommendation. Next claims this review for you.' },
    field('Human review', ai, 'Mandatory rationale', 'The query is confined to a fixed-data TypeScript test fixture excluded from production builds. The independent verifier agrees; accept the false-positive proposal.', 'A rationale records the reviewed evidence. Confidence by itself is insufficient to exempt a finding.'),
    click('Human review', ai, 'Accept false positive', 'Acceptance marks this fixture finding False positive and records the human decision.', s => s.ai.reviews[0].state === 'accepted'),
    read('Human review', ai, 'Verify the accepted decision', selector('[data-review-id="learn-review-1"]'), 'Review Accepted and the recorded rationale. The fixture finding is now exempt.', 'A human decision changes the finding outcome; an AI proposal alone does not.'),
    click('Human review', ai, 'Review the production proposal', 'The proposer suggests a false positive, while the independent verifier considers the issue sound.', shown(target('field', 'Mandatory rationale')), selector('[data-review-id="learn-review-2"]')),
    { ...click('Human review', ai, 'Claim review', 'Compare the independent verifier and policy reason before recording a decision.', s => s.ai.reviews[1].owner === REVIEWER), spotlight: selector('[data-ai-review-evidence]'), body: 'Read the evidence and the verifier disagreement below the AI recommendation. Next claims this review for you.' },
    field('Human review', ai, 'Mandatory rationale', 'Go production input reaches the lookup without recorded validation or parameter binding. The independent verifier disagrees with the proposer. Reject the exemption and retain the finding.', 'Disagreement requires evidence review. Rejecting the proposal keeps this finding in subsequent gates.'),
    click('Human review', ai, 'Reject proposal', 'Reject the false-positive proposal and reopen the production finding for triage.', s => s.ai.reviews[1].state === 'rejected'),
    read('Human review', ai, 'Verify the rejected decision', selector('[data-review-id="learn-review-2"]'), 'Review Rejected and the recorded rationale. This production finding remains eligible for gate evaluation.', 'Accepted and Rejected decisions are retained separately with their reviewer and version.'),
    click('Assignment & follow-up', findings, `Toggle details for ${AI_TITLES[1]}`, 'Open the retained production finding to triage and assign remediation.', shown(target('field', 'New comment'))),
    { ...field('Assignment & follow-up', findings, `Triage status for ${AI_TITLES[1]}`, 'Confirmed', 'Human triage confirms the retained finding after rejecting the AI exemption.', true), done: s => s.ai.findingStatus === 'confirmed' },
    click('Assignment & follow-up', findings, 'Admin User (user-001)', 'The assignee owns remediation; the AI review owner owns the proposal decision.', s => s.ai.assignedTo === REVIEWER),
    field('Assignment & follow-up', findings, 'New comment', 'Bind lookup parameters and add a regression test. Keep the finding gated until a comparable re-test verifies the fix.', 'Record the remediation plan and verification requirement for the assignee.'),
    click('Assignment & follow-up', findings, 'Post', 'Save the follow-up note with the confirmed finding.', s => Boolean(s.ai.comment)),
    read('Outcome', '/ai-triage/observability', 'Review AI outcomes', selector('[data-ai-outcomes="5"]'), 'Review five comparisons, two disagreements and one gate exemption (20%). Three additional proposals remain pending. Tokens and cost remain zero in this simulated exercise.', 'Observability helps assess proposal quality. These counters derive from all five training cases, including their language and CWE distributions.'),
    finish('ai', '/ai-triage/observability', selector('[data-ai-outcomes="5"]'), 'One fixture proposal was accepted; one production proposal was rejected, confirmed and assigned with a saved remediation plan. Three additional language and severity cases remain Pending.', s => s.ai.reviews[0].state === 'accepted' && s.ai.reviews[1].state === 'rejected' && Boolean(s.ai.assignedTo && s.ai.comment)),
  ],
  quality: [
    read('Project & analysis', '/code-quality', 'Start a code quality project', target('button', 'New project'), 'A Project retains source configuration, analysis history and a quality policy.', 'Quality analysis evaluates reliability, maintainability and security-sensitive code independently of the core scan walkthrough.'),
    click('Project & analysis', '/code-quality', 'New project', 'Create a project for the training repository.', shown(target('field', 'Name'))),
    field('Project & analysis', '/code-quality', 'Name', 'Checkout Quality', 'The name identifies the project in the portfolio.'),
    field('Project & analysis', '/code-quality', 'Key', PROJECT_KEY, 'The stable key identifies project history and links.'),
    field('Project & analysis', '/code-quality', 'Source', PROJECT_TARGET, 'This .example Git repository is simulated in your browser.'),
    field('Project & analysis', '/code-quality', 'Branch or tag', 'main', 'main is the baseline revision. The second analysis will evaluate the improved revision.'),
    { ...field('Project & analysis', '/code-quality', 'Quality policy', 'default', 'Synapse Way evaluates coverage and new critical issues. The walkthrough keeps the same policy for both revisions.'), target: selector('#project-gate'), example: { value: 'default' }, done: (_, doc) => doc.querySelector<HTMLSelectElement>('#project-gate')?.value === 'default' },
    click('Project & analysis', '/code-quality', 'Create and analyze', 'Save the project and start its first analysis.', s => Boolean(s.quality.project && s.quality.analyses.length)),
    read('Project & analysis', quality, 'Wait for baseline analysis', selector('[data-quality-analysis="learn-quality-analysis-main"]'), 'The analysis records ten issues across five languages and all five severity levels, three hotspots, 64% coverage and 5% duplication.', 'Wait for completed results before evaluating the gate.', s => Boolean(s.quality.analyses[0]?.finishedAt)),
    read('Quality gate', quality, 'Understand the failed gate', selector('[data-quality-analysis="learn-quality-analysis-main"]'), 'The baseline fails: two new critical issues exceed zero and 64% coverage is below the 80% threshold.', 'A gate is a policy verdict over measured results. Classifying an issue does not verify a fix.'),
    click('Issues & hotspots', `${quality}/issues`, 'Inspect a maintainability issue', 'Review the ten issues grouped by file, with distinct language, type and severity labels. Open the TypeScript validation issue and record acknowledged debt while the revision is prepared.', shown(selector('#issue-transition-rationale')), selector('[data-issue-id="learn-issue-1"]')),
    click('Issues & hotspots', `${quality}/issues`, 'Accepted', 'Accepted records acknowledged debt. It does not verify a source fix or revise the completed baseline gate.', (_, doc) => doc.querySelector('[data-issue-inspector="learn-issue-1"] [aria-pressed="true"]')?.textContent?.trim() === 'Accepted', selector('[data-issue-inspector="learn-issue-1"] button[aria-pressed]')),
    { ...field('Issues & hotspots', `${quality}/issues`, 'Rationale', 'Duplicated validation is acknowledged for consolidation in the next revision. Add regression coverage and analyze the updated code to verify improvement.', 'The classification records reviewed evidence and the planned fix.'), target: selector('#issue-transition-rationale') },
    click('Issues & hotspots', `${quality}/issues`, 'Apply Classification', 'Save the versioned classification with its rationale.', s => s.quality.issueStatus === 'accepted'),
    click('Issues & hotspots', `${quality}/hotspots`, 'Inspect the security hotspot', 'Review the TypeScript checksum, Go TLS client and Python logging hotspots. A hotspot identifies a security-sensitive pattern that needs context review; examine the checksum first.', shown(selector('[aria-label="Hotspot inspector"]')), selector('[data-hotspot-id="learn-hotspot-1"]')),
    click('Issues & hotspots', `${quality}/hotspots`, 'Review & Audit', 'Review how the checksum is used before recording Safe.', shown(selector('#rationale'))),
    click('Issues & hotspots', `${quality}/hotspots`, 'Safe', 'The checksum detects changes in public cached assets and performs no security decision.', (_, doc) => doc.querySelector('[aria-label="Hotspot inspector"] [aria-pressed="true"]')?.textContent?.trim().startsWith('Safe') === true, selector('[aria-label="Hotspot inspector"] button[aria-pressed]')),
    { ...field('Issues & hotspots', `${quality}/hotspots`, 'Rationale', 'Reviewed the cache checksum: it detects changes in public assets and is not used for passwords, signatures or security decisions.', 'Safe records the reviewed usage; it does not weaken the quality gate.'), target: selector('#rationale') },
    click('Issues & hotspots', `${quality}/hotspots`, 'Save Decision', 'Save the hotspot decision and audit history.', s => s.quality.hotspotStatus === 'safe'),
    simulation('Re-analysis & comparison', quality, 'Load the improved source revision', selector('main'), '/playground/quality/improve', 'The simulated revision remediates all ten issues, verifies TLS, redacts diagnostic logs and adds regression tests. The checksum remains Safe; the other two hotspots become Fixed after analysis. It changes source results, not gate thresholds.', s => Boolean(s.quality.improvedAt)),
    click('Re-analysis & comparison', quality, 'Run analysis', 'Analyze improved using the same policy. The baseline remains retained in history.', s => s.quality.analyses.length === 2),
    read('Re-analysis & comparison', quality, 'Verify the improved analysis', selector('[data-quality-analysis="learn-quality-analysis-improved"]'), 'Wait for the revised analysis: zero open issues, 86% coverage, 1% duplication and a Passed gate.', 'Completed analysis supplies the evidence for improvement.', s => Boolean(s.quality.analyses[1]?.finishedAt)),
    read('Re-analysis & comparison', `${quality}/compare?base=main&head=improved`, 'Compare the two revisions', selector('[data-quality-base="learn-quality-analysis-main"][data-quality-head="learn-quality-analysis-improved"] [data-quality-metric-comparison]'), 'Review main against improved: Failed → Passed, coverage 64% → 86% and duplication 5% → 1%.', 'Both revisions use Synapse Way. Compare measured results and ratings before concluding the changes improved quality.', s => Boolean(s.quality.analyses[1]?.finishedAt)),
    finish('quality', `${quality}/compare?base=main&head=improved`, selector('[data-quality-base="learn-quality-analysis-main"][data-quality-head="learn-quality-analysis-improved"]'), 'The project retains its baseline, issue classification, hotspot audit decision and improved analysis with a passing gate.', s => s.quality.analyses.length === 2 && s.quality.analyses.every(a => Boolean(a.finishedAt)) && s.quality.hotspotStatus === 'safe'),
  ],
}
export function workflowRoute(mode: WorkflowMode, s: Workflows) { return WORKFLOW_STEPS[mode][Math.min(s[mode].step, WORKFLOW_STEPS[mode].length - 1)].route }
