// Package shared holds value objects and errors common to all domain packages.
// It must not import any other internal package (innermost layer of the onion).
package shared

import (
	"errors"
	"time"
)

// ID is a domain identifier (opaque string; generated by the platform layer).
type ID string

func (id ID) String() string { return string(id) }
func (id ID) IsZero() bool   { return id == "" }

// DefaultTenant is the non-empty tenant id the empty-string (single-tenant) default maps to. RLS
// tables treat the empty string as DENY, so the default deployment uses this id (it matches the
// fleet DefaultFleetTenant and the seeded 'default' tenant row). Use TenantOrDefault to normalize.
const DefaultTenant ID = "default"

// TenantOrDefault returns id, or DefaultTenant when id is empty — so a single-tenant empty tenant and
// the fleet 'default' tenant resolve to the same RLS partition (letting, e.g., an image scan and the
// cluster/host agent that observes it correlate under one tenant).
func TenantOrDefault(id ID) ID {
	if id.IsZero() {
		return DefaultTenant
	}
	return id
}

// Severity is the normalized severity scale shared by findings and vulnerabilities.
type Severity string

const (
	SeverityCritical Severity = "critical"
	SeverityHigh     Severity = "high"
	SeverityMedium   Severity = "medium"
	SeverityLow      Severity = "low"
	SeverityInfo     Severity = "info"
	SeverityUnknown  Severity = "unknown"
)

// Sentinel errors mapped to transport status codes by the adapter layer.
var (
	ErrValidation = errors.New("validation error")
	ErrNotFound   = errors.New("not found")
	ErrForbidden  = errors.New("forbidden")        // scope / authorization-window violations
	ErrConflict   = errors.New("conflict")         // optimistic-concurrency version mismatch (lost-update guard)
	ErrSaturated  = errors.New("system saturated") // bounded admission rejected (backpressure → 503)
)

// severityVocabulary is shared by validation and schema contract tests.
var severityVocabulary = [...]Severity{SeverityCritical, SeverityHigh, SeverityMedium, SeverityLow, SeverityInfo, SeverityUnknown}

// AllSeverities returns a defensive copy of all accepted severity labels.
func AllSeverities() []Severity {
	return append([]Severity(nil), severityVocabulary[:]...)
}

// Valid reports whether s is a known severity label.
func (s Severity) Valid() bool {
	for _, allowed := range severityVocabulary {
		if s == allowed {
			return true
		}
	}
	return false
}

// SeverityRank orders severity from unknown (0) to critical (5); used for
// thresholds and tie-breaks.
func SeverityRank(s Severity) int {
	switch s {
	case SeverityCritical:
		return 5
	case SeverityHigh:
		return 4
	case SeverityMedium:
		return 3
	case SeverityLow:
		return 2
	case SeverityInfo:
		return 1
	default:
		return 0
	}
}

// Audit holds common audit timestamps embedded by entities.
type Audit struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	// CreatedBy / UpdatedBy attribute a record to the actor that created / last modified it
	// (ownership). Empty = system/unknown (legacy rows, or write paths not yet wired).
	// Engagements persist these; other record types carry the fields and adopt persistence
	// incrementally – the canonical home so ownership is one shape across the domain.
	CreatedBy string
	UpdatedBy string
}
